package io.geekmind.budgie.model.dto;

/**
 * Defines the types of balance generated by the application.
 *
 * @author Andre Silva
 */
public enum BalanceType {
    BUDGET_TEMPLATE_BALANCE,
    REGULAR_PERIOD_BALANCE
}
