spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_budgie
    username: postgres
    password: password
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    enabled: false

budgie:
  encrypt:
    textFieldSecretPhrase: textFieldSecretPhrase
    decimalFieldSecretPhrase: decimalFieldSecretPhrase

