spring:
  resources:
    cache:
      cachecontrol:
        cache-private: true
  datasource:
    driver-class-name: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    url: ${DATABASE_URL}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    url: ${spring.datasource.url}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
