spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_budgie
    username: postgres
    password: password
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
#  security:
#    enabled: false

budgie:
  encrypt:
    textFieldSecretPhrase: textFieldSecretPhrase
    decimalFieldSecretPhrase: decimalFieldSecretPhrase
    byteFieldSecretPhrase: byteFieldSecretPhrase
  auth:
    username: JDJhJDEwJGNSQlBDL0szalRKeXdDdW40Wldxcy5CSExUN0xoaTl2Li5LREtuWWdpZmVpenRxS2p4ZHpx # user
    password: JDJhJDEwJDNpWGJicUVMaWIwSWZlaWF3ajFwN3VjWVh5VUJUM2VsalFPRm9Zem5RVmpXdU9ZUy9GLjMu # password

